Added documentation and Travis script for building on MacOS
openzim/zimwriterfs pull request #82
Opened 2018-09-19 13:57 UTC by ISNIT0

2018-09-19 14:29 UTC, ISNIT0 commented
@mgautierfr Could you set up signing and distribution please?

2018-10-02 08:46 UTC, mgautierfr requested changes
I'm a bit disturbed by this.
Historically, this is the travis in `kiwix-build` that publish things. The individual project's CIs are used to ensure the a change in this project is correct.
If we publish things in `zimwriterfs` CI, we will not be able to publish a new build version of `zimwriterfs` in we change `libzim` only. (And `zimwriterfs` CI has no access to ssh keys).

2018-10-02 08:46 UTC, mgautierfr commented on travis/compile.sh
> +  cp -r build/src/* ./zimwriterfs
Why copy all the src content ?
We only need the `zimwriterfs` binary no ?
But, we are compiling dynamically on osx, so we probably need to package the library dependencies also.
I'm not sure how appdmg does it (if it does it)

2018-10-02 08:46 UTC, mgautierfr commented on appdmg.json
> +    },
zimwriterfs is a console application, what the `window` is for ?
(same question for the `x` and `y` above)

2018-10-03 08:42 UTC, mgautierfr commented
Have you seen this http://mesonbuild.com/Creating-OSX-packages.html ?

2019-03-01 08:53 UTC, kelson42 commented
@ISNIT0 Would you be able to work with Matthieu to polish this PR and get it merged?

2020-06-07 12:45 UTC, closed without merging